services:
  postgres:
    image: postgres:16-alpine
    container_name: edugov_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: education_news_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_secure_password_2026
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: edugov_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: edugov_web
    restart: unless-stopped
    command: >
      sh -c "python manage.py migrate &&
             python manage.py seed_education_data &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3"
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - SECRET_KEY=django-prod-secret-key-education-portal-secure
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=education_news_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres_secure_password_2026
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  celery_worker:
    build: .
    container_name: edugov_celery_worker
    restart: unless-stopped
    command: celery -A core worker -l info
    volumes:
      - .:/app
      - media_volume:/app/media
    environment:
      - DEBUG=False
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=education_news_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres_secure_password_2026
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

  celery_beat:
    build: .
    container_name: edugov_celery_beat
    restart: unless-stopped
    command: celery -A core beat -l info
    volumes:
      - .:/app
    environment:
      - DEBUG=False
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=education_news_db
      - DB_USER=postgres
      - DB_PASSWORD=postgres_secure_password_2026
      - DB_HOST=postgres
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - postgres
      - redis

volumes:
  postgres_data:
  media_volume:
