# Generated by Django 6.1 on 2026-08-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the education category', max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL slug', max_length=150, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description for SEO and category page header')),
                ('icon', models.CharField(blank=True, default='newspaper', help_text='Icon identifier (e.g. newspaper, award, id-card, book)', max_length=60)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Ordering in navigation and lists (lower numbers come first)')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this category is displayed publicly')),
                ('meta_title', models.CharField(blank=True, help_text='SEO Meta Title (optional override)', max_length=200)),
                ('meta_description', models.CharField(blank=True, help_text='SEO Meta Description (optional override)', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='categories__slug_9b1a28_idx'), models.Index(fields=['is_active', 'display_order'], name='categories__is_acti_55dc45_idx')],
            },
        ),
    ]
