# Generated by Django 6.1 on 2026-08-28 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Source identifier e.g. 'SSC Official Notices'", max_length=150, unique=True)),
                ('url', models.URLField(help_text='Target URL to fetch notices/updates from', max_length=500)),
                ('official_domain', models.CharField(help_text="e.g. 'ssc.gov.in', 'upsc.gov.in', 'nta.ac.in'", max_length=200)),
                ('source_type', models.CharField(choices=[('html', 'HTML Webpage'), ('pdf', 'PDF Direct Notice'), ('rss', 'RSS / Atom Feed'), ('api', 'JSON / REST API'), ('sitemap', 'XML Sitemap')], default='html', max_length=20)),
                ('parser', models.CharField(choices=[('ssc', 'SSC (Staff Selection Commission)'), ('upsc', 'UPSC (Union Public Service Commission)'), ('nta', 'NTA (National Testing Agency)'), ('railway', 'Railway Recruitment (RRB / RRC)'), ('generic_rss', 'Generic RSS/Atom Feed'), ('generic_html', 'Generic HTML Notice Board')], default='generic_html', max_length=50)),
                ('fetch_frequency_minutes', models.PositiveIntegerField(default=30, help_text='Frequency to poll in minutes (e.g. 15, 30, 60)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable automated fetching')),
                ('auto_publish', models.BooleanField(default=True, help_text='Auto-publish articles if validated, or send to Admin Review')),
                ('priority', models.PositiveIntegerField(default=10, help_text='Fetch priority (lower number = higher priority)')),
                ('config', models.JSONField(blank=True, default=dict, help_text='Optional custom configuration (CSS selectors, custom headers, auth, etc.)')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('error_count', models.PositiveIntegerField(default=0)),
                ('last_error_message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('idle', 'Idle / Ready'), ('fetching', 'Fetching'), ('success', 'Success'), ('error', 'Error'), ('disabled', 'Disabled')], default='idle', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, help_text='Default category if auto-detection falls back', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='categories.category')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='FetchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partial', 'Partial'), ('failed', 'Failed')], max_length=20)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('items_found', models.PositiveIntegerField(default=0)),
                ('items_new', models.PositiveIntegerField(default=0)),
                ('items_duplicate', models.PositiveIntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fetch_logs', to='sources.source')),
            ],
            options={
                'verbose_name': 'Fetch Log',
                'verbose_name_plural': 'Fetch Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, db_index=True, help_text='Unique ID or hash from source', max_length=255)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000)),
                ('content_hash', models.CharField(db_index=True, help_text='SHA256 of normalized title & URL', max_length=64)),
                ('raw_data', models.JSONField(default=dict, help_text='Extracted raw metadata, dates, links, and text')),
                ('status', models.CharField(choices=[('new', 'New / Unprocessed'), ('processed', 'Processed'), ('duplicate', 'Duplicate Skipped'), ('error', 'Processing Error')], default='new', max_length=20)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sources.source')),
            ],
            options={
                'verbose_name': 'Source Item',
                'verbose_name_plural': 'Source Items',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='RawDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('pdf', 'PDF Document'), ('html', 'HTML Snapshot'), ('json', 'JSON Response')], default='pdf', max_length=20)),
                ('file_url', models.URLField(max_length=1000)),
                ('local_file', models.FileField(blank=True, null=True, upload_to='raw_docs/%Y/%m/')),
                ('extracted_text', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sources.sourceitem')),
            ],
            options={
                'verbose_name': 'Raw Document',
                'verbose_name_plural': 'Raw Documents',
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('fetch', 'Source Fetch'), ('parse', 'Content Parsing'), ('pdf', 'PDF Processing'), ('classify', 'Category & Template Classification'), ('dedup', 'Duplicate Detection'), ('generate', 'Article Generation'), ('validate', 'Data Validation'), ('publish', 'Publishing')], max_length=20)),
                ('status', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('message', models.CharField(max_length=500)),
                ('error_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processing_logs', to='articles.article')),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='processing_logs', to='sources.sourceitem')),
            ],
            options={
                'verbose_name': 'Processing Log',
                'verbose_name_plural': 'Processing Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='sourceitem',
            index=models.Index(fields=['source', 'content_hash'], name='sources_sou_source__959a23_idx'),
        ),
        migrations.AddIndex(
            model_name='sourceitem',
            index=models.Index(fields=['status'], name='sources_sou_status_34cd06_idx'),
        ),
    ]
