# Generated by Django 6.1 on 2026-08-28 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('related_result', 'Related Result'), ('related_admit_card', 'Related Admit Card'), ('related_exam', 'Related Exam Notice'), ('related_recruitment', 'Related Recruitment'), ('general_related', 'Related Article')], default='general_related', max_length=30)),
                ('anchor_text', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article Internal Link',
                'verbose_name_plural': 'Article Internal Links',
            },
        ),
        migrations.CreateModel(
            name='ArticleTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('result', 'Result Template'), ('admit_card', 'Admit Card Template'), ('recruitment', 'Recruitment / Vacancy Template'), ('exam', 'Exam / Notification Template'), ('answer_key', 'Answer Key Template'), ('general_news', 'General Education News Template')], max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('structure_json', models.JSONField(default=dict, help_text='Template schema defining required sections, fields, and default FAQ structure')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=350)),
                ('content_html', models.TextField()),
                ('structured_data', models.JSONField(default=dict)),
                ('change_summary', models.CharField(blank=True, help_text='Explanation of what changed in official notice', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article Version',
                'verbose_name_plural': 'Article Versions',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='SEOMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('canonical_url', models.URLField(blank=True, max_length=500)),
                ('og_image', models.URLField(blank=True, max_length=500)),
                ('schema_type', models.CharField(default='NewsArticle', max_length=50)),
                ('custom_json_ld', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SEO Metadata',
                'verbose_name_plural': 'SEO Metadata',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Headline for the article', max_length=350)),
                ('slug', models.SlugField(blank=True, max_length=380, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short 2-3 sentence summary for news lists and SEO', max_length=600)),
                ('content_html', models.TextField(help_text='Full semantic HTML content generated from official source')),
                ('structured_data', models.JSONField(blank=True, default=dict, help_text='Structured facts (dates, links, steps, eligibility, FAQs)')),
                ('official_url', models.URLField(help_text='Direct official notice webpage', max_length=1000)),
                ('official_pdf_url', models.URLField(blank=True, help_text='Official PDF download link if available', max_length=1000)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('processing', 'Processing'), ('review', 'Pending Review'), ('published', 'Published'), ('updated', 'Updated'), ('rejected', 'Rejected'), ('duplicate', 'Duplicate'), ('error', 'Error')], db_index=True, default='draft', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature in top editorial spot on homepage')),
                ('is_breaking', models.BooleanField(default=False, help_text='Display in breaking updates ticker')),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('reading_time_mins', models.PositiveIntegerField(default=2)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='categories.category')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
