# Generated by Django 6.1 on 2026-08-28 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
        ('sources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='sources.source'),
        ),
        migrations.AddField(
            model_name='article',
            name='source_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='sources.sourceitem'),
        ),
        migrations.AddField(
            model_name='articlelink',
            name='source_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='articles.article'),
        ),
        migrations.AddField(
            model_name='articlelink',
            name='target_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='articles.article'),
        ),
        migrations.AddField(
            model_name='article',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='articles.articletemplate'),
        ),
        migrations.AddField(
            model_name='articleversion',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='articles.article'),
        ),
        migrations.AddField(
            model_name='seometadata',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo_meta', to='articles.article'),
        ),
        migrations.AlterUniqueTogether(
            name='articlelink',
            unique_together={('source_article', 'target_article')},
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['status', '-published_at'], name='articles_ar_status_de59cf_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category', 'status', '-published_at'], name='articles_ar_categor_a78618_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='articles_ar_slug_452037_idx'),
        ),
    ]
