# Generated by Django 6.1 on 2026-08-28 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='EduGov News', max_length=150)),
                ('site_tagline', models.CharField(default='Instant & Verified Official Education Updates, Results, Admit Cards & Jobs', max_length=250)),
                ('meta_description', models.TextField(default='Official education news portal providing real-time government notifications, exam schedules, admit cards, recruitment notices, and result direct links.')),
                ('contact_email', models.EmailField(default='contact@edugovnews.org', max_length=254)),
                ('disclaimer_text', models.TextField(default='Disclaimer: This website is an independent education information portal. We curate and aggregate public notifications from official government portals. We are not associated with any government ministry, board, or commission. Always refer to official government websites for primary validation.')),
                ('top_breaking_announcement', models.CharField(blank=True, help_text='Global pinned notice displayed in the top bar', max_length=300)),
                ('enable_ads', models.BooleanField(default=False, help_text='Toggle display of reserved ad slots')),
                ('ad_top_banner', models.TextField(blank=True, help_text='HTML / Script code for 728x90 top header banner')),
                ('ad_sidebar', models.TextField(blank=True, help_text='HTML / Script code for 300x250 or 300x600 sidebar ad')),
                ('ad_in_article', models.TextField(blank=True, help_text='HTML / Script code for in-content ad slot')),
                ('ad_between_news', models.TextField(blank=True, help_text='HTML / Script code for news list separator ad')),
                ('google_analytics_id', models.CharField(blank=True, help_text='e.g. G-XXXXXXXXXX', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
